"""Compile user-editable JSON to fixed-sector TF payload and 16x16 glyph ROM.
Run from the meetings directory. No disk writes: meeting.bin is an image fragment.
Glyph IDs are an explicit private encoding, not UTF-8. Regenerate ROM with payload.
"""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# 字模字体: 全工程统一为思源黑体 / Noto Sans SC(与 tools/gen_osd_font.py、
# tools/gen_emergency_osd.py 同源), 16px 直渲。原为 simhei.ttf(黑体)。
# ★字号取 15 而非 16: 思源黑体的字形比黑体大一号, 16px 时墨盒高可达 17px
#   (142 字里 24 个超出 16 行 → 每格顶行被裁 1px); 15px 时仅 2 个为 17px,
#   平均墨高 14.49(原黑体 16px 为 13.92), 观感与原来最接近且基本不裁。
FONT_PATH = 'C:/Windows/Fonts/Noto Sans SC (TrueType).otf'
FONT_SIZE = 15

root = Path(__file__).resolve().parents[1]
d = json.loads((root/'assets/meeting.json').read_text(encoding='utf-8'))
labels = ['当前议题：', '发言人：', '剩余时间', '已超时', '议程', '下一项：', '下一位：', '计划时间：',
          '等待开始', '会议进行', '会议暂停', '发言即将结束', '发言时间已到', '切换议题', '会议结束',
          '会议因告警暂停', '紧急告警请按指引疏散', '系统运行时间', '议程总览', '没有下一项',
          'KEY1开始暂停继续 KEY2下一项 KEY3上一项 KEY4重新计时']
strings = [d['meeting'],d['organizer'],d['venue'],*d['notices'],*labels]
for a in d['agenda']: strings += [a['title'],a['speaker']]
chars = list(dict.fromkeys(' '+'0123456789:/'+''.join(strings)))
assert len(chars)<=256
ids={c:i for i,c in enumerate(chars)}
def field(s,n):
    if len(s)>n: raise ValueError(f'text exceeds {n} cells: {s}')
    return bytes(ids[c] for c in s.ljust(n))
n=len(d['agenda']); assert 1<=n<=16 and len(d['notices'])==4
payload=bytearray(b'MTG1'+bytes([n]))
for s in strings[:7]: payload+=field(s,40)
for a in d['agenda']:
    assert 1<=a['seconds']<=5999
    payload+=a['seconds'].to_bytes(2,'big')+field(a['title'],40)+field(a['speaker'],20)
payload+=bytes((-len(payload))%512)
(root/'assets/meeting.bin').write_bytes(payload)
(root/'assets/meeting.hex').write_text('\n'.join(f'{b:02x}' for b in payload)+'\n',encoding='ascii')
(root/'assets/encoding.json').write_text(json.dumps(chars,ensure_ascii=False),encoding='utf-8')
font=ImageFont.truetype(FONT_PATH,FONT_SIZE)
rows=[]
for ch in chars:
    im=Image.new('L',(16,16)); draw=ImageDraw.Draw(im); box=draw.textbbox((0,0),ch,font=font)
    draw.text(((16-(box[2]-box[0]))//2-box[0],(16-(box[3]-box[1]))//2-box[1]),ch,font=font,fill=255)
    # 判墨阈值 64(原 96): 思源黑体笔画比黑体细, 15px 时降到 64 后总墨点数
    # 11221 ≈ 原黑体 16px 的 11379, 观感粗细基本不变。
    for y in range(16): rows.append(sum((im.getpixel((x,y))>=64)<<(15-x) for x in range(16)))
rows += [0]*(4096-len(rows))
(root/'assets/glyphs.hex').write_text('\n'.join(f'{r:04x}' for r in rows)+'\n',encoding='ascii')
lines=['// Generated by build_assets.py. Compatible with existing 16x16 MSB-left convention.',
       'module meeting_glyph_rom(input [11:0] addr, output [15:0] q);',
       'reg [15:0] mem[0:4095]; /* fehdl force_ram=1, ram_style="bram" */',
       'initial begin']
lines += [f'mem[{i}]=16\'h{r:04x};' for i,r in enumerate(rows)]
lines += ['end','assign q=mem[addr];','endmodule']
(root/'rtl/meeting_glyph_rom.v').write_text('\n'.join(lines)+'\n',encoding='ascii')
def pack(s): return "320'h"+field(s,40).hex()
inc=['// Generated private glyph encoding; char 0 occupies bits 319:312.']
for i,s in enumerate(labels): inc.append(f'localparam [319:0] TEXT_{i} = {pack(s)};')
inc += ['function [7:0] digit_id; input integer n; begin case(n)']
inc += [f'{i}: digit_id=8\'d{ids[str(i)]};' for i in range(10)]
inc += ['default: digit_id=0; endcase end endfunction',f'localparam [7:0] COLON_ID=8\'d{ids[":"]}, SLASH_ID=8\'d{ids["/"]};']
(root/'rtl/meeting_text.vh').write_text('\n'.join(inc)+'\n',encoding='ascii')
print(f'{n} agenda items, {len(chars)} glyphs, {len(payload)} bytes / {len(payload)//512} sectors')
